# -*- coding: utf-8 -*-
"""#2577

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NLUXlbLZZw6zJ8kbbDZtRcORVZMO_0em
"""

# 2577 숫자의 개수

count = [0] * 10 # 숫자를 셀 리스트 생성

A = int(input())
B = int(input())
C = int(input())

result = A * B * C

for i in range(len(str(result))):
    num = result % 10
    result = result // 10
    
    count[num] += 1

for i in range(10):
    print(count[i])