# -*- coding: utf-8 -*-
"""# 11719

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NV6CfnTJWMWhDKq9AkArmZUsAtEvpwku
"""

# 11719 그대로 출력하기2
while 1:
    try:
        print(input())
    except EOFError:
        break;