# -*- coding: utf-8 -*-
"""# 2293

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e9UmxULWWifAostgIJuGSb_aTNJfm276
"""

# 2293 동전 1
import sys
input = sys.stdin.readline

n, k = map(int, input().split())
dp = [0 for _ in range(k+1)]
dp[0] = 1
coin = []

for _ in range(n):
    coin.append(int(input()))

for i in coin:
    for j in range(i, k+1):
        if j-i >= 0:
            dp[j] += dp[j-i]

print(dp[-1])