# -*- coding: utf-8 -*-
"""# 2920

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eLzD4hA4f-l2aDThaomBKx7zuok_SOr
"""

# 2920 음계
ascending = [1, 2, 3, 4, 5, 6, 7, 8]
descending = [8, 7, 6, 5, 4, 3, 2, 1]

music = list(map(int, input().split()))

if music == ascending:
    print('ascending')
elif music == descending:
    print('descending')
else:
    print('mixed')