# -*- coding: utf-8 -*-
"""# 12790

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HgCoPX_K-0QSYRVyAC4AuZi40U2IEwK5
"""

# 12790 Mini Fantasy War
T = int(input())

for i in range(T):
    HP, MP, attack, shield, HP_change, MP_change, attack_change, shield_change = map(int ,input().split())
    HP = HP + HP_change
    MP = MP + MP_change
    attack = attack + attack_change
    shield = shield + shield_change

    if HP < 1:
        HP = 1
    if MP < 1:
        MP = 1
    if attack < 0:
        attack = 0
    
    power = HP + 5*MP + 2*attack + 2*shield
    print(power)