# -*- coding: utf-8 -*-
"""#1546

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRb5utTTF-ECv0KsrvyzrDPjGlMxQsXZ
"""

# 1546 평균

N = int(input()) # 과목의 수
score = list(map(int, input().split())) # 과목별 점수 저장

M = max(score) # 최고점

for i in range(N):
    score[i] = (score[i] / M) * 100

print(sum(score) / N)