# -*- coding: utf-8 -*-
"""# 9372

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PjOe1PmfP7fs6cEek11b8fg0lJrwGBl1
"""

import sys 
T = int(input())
for i in range(T):
    N, M = map(int, sys.stdin.readline().split()) # sys.stdin.readline()을 통해 여러줄 입력받을 떄 시간을 줄인다.
    for j in range(M):
        A, B = map(int, sys.stdin.readline().split()) # 사실 이 입력은 정답과 큰 연관은 없다.
    print(N - 1) # 국가 수 - 1