# -*- coding: utf-8 -*-
"""# 10250

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3g0xzsTpcjqoc3UUSPe9TjBYLIEnfJs
"""

# 10250 ACM 호텔
T = int(input()) # 테스트 케이스 개수


for i in range(T):
    X = 1 # 기본적으로 1호
    H, W, N = map(int, input().split())
    Y = str(N % H) # 층 수
    X += N // H # 호 수

    if (N%H) == 0:
        Y = str(H)
        X -= 1

    X = str(X)

    if len(X) == 1:
        X = '0' + str(X)

    print(Y+X)