# -*- coding: utf-8 -*-
"""# 5397

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oMDwqhKeXUcmSzKAvpz1ykUpSsvxxB9b
"""

# 5397 키로거
from collections import deque
import sys
T = int(input())

for _ in range(T):
    seq = deque(sys.stdin.readline().rstrip())
    l, r = [], [] # 스택!

    # 입력한 키 조회
    while seq:
        key = seq.popleft() # 왼쪽이 먼저 입력
        # 입력 별 처리
        if key == '<':
            if l:
                r.append(l.pop())
        elif key == '>':
            if r:
                l.append(r.pop())
        elif key == '-':
            if l:
                l.pop()
        else:
            l.append(key)
    # 오른쪽 처리
    while r:
        l.append(r.pop())

    print("".join(l))