# -*- coding: utf-8 -*-
"""# 16171

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ls8nEtrthTVstkbYBOQ8wzVbS7iLmV-f
"""

# 16171 나는 친구가 적다 (Small)
S = input()
K = input()

nums = "0123456789"

newS = ""
for i in range(len(S)):
    if not(S[i] in nums):
        newS += S[i]

if K in newS:
    print(1)
else:
    print(0)