# -*- coding: utf-8 -*-
"""# 1476

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eWTp1c5qHT30kv3HmT1iXMk76hQwXfD4
"""

# 1476 날짜 계산
E, S, M = map(int, input().split());
cnt = 1
cnt_E, cnt_S, cnt_M = 1, 1, 1

while 1:

    if cnt_E == E and cnt_S == S and cnt_M == M:
        break

    cnt += 1
    cnt_E  += 1
    cnt_S  += 1
    cnt_M  += 1

    if cnt_E == 16:
        cnt_E = cnt_E%15
    if cnt_S == 29:
        cnt_S = cnt_S%28
    if cnt_M == 20:
        cnt_M = cnt_M%19

print(cnt)