# -*- coding: utf-8 -*-
"""# 1934

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19qi8pFqhg5YAiv5Hf4Ct_ZpwOLmGdxyH
"""

# 1934 최소공배수
import sys
def gcd(a, b): # 자연수만 고려한 최대 공약수
    if a < b :
        a, b = b, a

    while b != 0:
        r = a%b
        a, b = b, r

    return a

# Solution
T = int(input())

for _ in range(T):
    A, B = map(int, sys.stdin.readline().split())
    print( A * B // gcd(A,B) )