# -*- coding: utf-8 -*-
"""# 1356

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B00LIivEB4HuVxbJbP9zyvT8Z3tOtTAz
"""

# 1356 유진수

N = input()
check = False # 유진수인지 아닌지

for i in range(1,len(N)):
    N_front = N[:i]
    N_back = N[i:]

    front_mult = 1
    back_mult = 1

    for j in N_front:
        front_mult *= int(j)
    for k in N_back:
        back_mult *= int(k)
    
    if front_mult == back_mult:
        check = True
        break;

if check == True:
    print('YES')
else:
    print('NO')