# -*- coding: utf-8 -*-
"""# 2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AyLk4gGs-AmceBzDtLUEUvhFHmKi20sY
"""

# 2023
N=int(input())

# 소수 판별
def isPrime(n):
    if(N<2): # ~1 ㅃㅃ
        return False
    for i in range(2, int(n**0.5)+1):
        if(n%i == 0):
            return False
    return True

def dfs(num):
    if (len(str(num))== N):
        print(num)
    else:
        for i in range(10): # 0~9
            temp = num*10 + i
            if isPrime(temp):
                dfs(temp)

dfs(2)
dfs(3)
dfs(5)
dfs(7)