# -*- coding: utf-8 -*-
"""# 1138

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gx8xjOhpRAnbtLXzVf7K4sBGM79NaWNZ
"""

# 1138 한 줄로 서기
N = int(input())
line = [0 for _ in range(N)]
ary = list(map(int, input().split()))

for i in range(N):
    cnt = 0
    for j in range(N):
        if cnt == ary[i] and not line[j]:
            line[j] = i + 1
            break
        elif not line[j]:
            cnt += 1

print(*line)