# -*- coding: utf-8 -*-
"""# 5523

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nC_NcZQ0EUqCghzGhEul_FK5DlcvYqV3
"""

# 5523 경기 결과
import sys
N = int(sys.stdin.readline())

win_A = 0
win_B = 0

for i in range(N):
    Ai, Bi = map(int, sys.stdin.readline().split())
    if Ai > Bi:
        win_A += 1
    elif Ai < Bi:
        win_B += 1

print(win_A, win_B)