# -*- coding: utf-8 -*-
"""# 15894

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SemwuJTelqk6gbczFiN5nWxgXmt1aDbW
"""

# 15894 수학은 체육과목 입니다
print(int(input()) * 4)