# -*- coding: utf-8 -*-
"""#2941

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sBqnMdZxM6nNCABmBfotPwpKx5qaFYda
"""

# 2941 크로아티아 알파벳 

cro = ['c=','c-','dz=','d-','lj','nj','s=','z=']

word = input()

for i in cro:
    word = word.replace(i,'a')

print(len(word))