# -*- coding: utf-8 -*-
"""# 1456

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vAOUKcYVBx38rXbzRwec4O4CR45JbEN0
"""

# 1456 거의 소수
A, B = map(int, input().split())

eratos = [True for _ in range( int(B**0.5) + 1 )]
length = len(eratos)
cnt = 0

# 에라토스테네스의 체
for i in range(2, length): 
    if eratos[i] == True:
        for j in range(2*i, length, i):
            eratos[j] = False

primes = [i for i in range(2,length) if eratos[i]]
# 구한 소수들 기준으로 count
for i in primes:
    num = i
    i *= num
    while i <= B:
        if A <= i:
            cnt += 1
        i *= num

print(cnt)