# -*- coding: utf-8 -*-
"""# 15552

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yl4zOtHrPwIxYOD-kp4kn8RTt-8ab8bX
"""

# 15552 빠른 A + B
import sys
T = int(sys.stdin.readline())
for i in range(T):
    A, B = map(int, sys.stdin.readline().split())
    print(A + B)