# -*- coding: utf-8 -*-
"""# 2748

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q8Ym6JeJE0HLzW-u1skIdQCPz-CBTKG2
"""

# 2748 피보나치 수 2
Fibonacci = [0 for _ in range(91)]
Fibonacci[1] = 1

for i in range(2, 91):               
    Fibonacci[i] = Fibonacci[i-1] + Fibonacci[i-2] 

n = int(input()) 
print(Fibonacci[n])