# -*- coding: utf-8 -*-
"""# 1654

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SincWaPl--Z3W1T-uj96cPy8PJY1e-4a
"""

# 1654 랜선 자르기
import sys
K, N = map(int, input().split())
line = []

for _ in range(K):
    line.append(int(sys.stdin.readline()))

# binary search
start, end = 1, max(line)
while start <= end:
    cut = 0 # 잘린 선 수
    mid = (start + end) // 2

    for  l in line:
        cut += l//mid

    if cut >= N: 
        start = mid + 1
        ans = mid # 정답은 이 상황을 만족해야함
    else:
        end = mid -1

print(ans)