# -*- coding: utf-8 -*-
"""# 1929

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10oj0zcmHylqM-2mRF9oiF7dwGhv-SrI3
"""

# 1929 소수 구하기
def PrimeCheck(num):
    if num==1:
        return False
    else:
        for i in range(2, int(num**0.5)+1): # 2부터 해당 수의 제곱근까지만 검사를 해주면 된다.
            if num%i == 0:
                return False
        return True

M, N = map(int, input().split())

for j in range(M, N+1):
    if PrimeCheck(j): # j에 해당하는 값이 PrimeCheck 함수에서 True라면.
        print(j) # j를 그대로 출력한다.