# -*- coding: utf-8 -*-
"""# 15649

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19jviPzShXNOR6SrpkY4JVEASUaQfJ6xz
"""

# 15649 N과 M (1)
N, M = map(int, input().split())
ary = []

def dfs():
    if len(ary) == M:
        print(' '.join(map(str, ary)))
        return
    
    for i in range(N):
        if i+1 not in ary:
            ary.append(i+1)
            dfs()
            ary.pop()
dfs()