# -*- coding: utf-8 -*-
"""# 1002

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13y-xFJ1_uShtLGeIn4N-DxFppLfTvxjb
"""

# 1002 터렛
T = int(input())
for i in range(T):
    x1, y1, r1, x2, y2, r2 = map(int, input().split())
    distance = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5 # 원의 중심 사이의 거리
    
    r_sum = r1 + r2
    r_difference = abs(r1 - r2)

    if distance == 0:
        if r1 == r2:
            print(-1)
        else:
            print(0)
    else:
        if distance == r_sum or distance == r_difference:
            print(1)
        elif distance < r_sum and distance > r_difference:
            print(2)
        else:
            print(0)