# -*- coding: utf-8 -*-
"""# 1735

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1piEXUCOUCo6l-RbaPUz4pPbJuNZqj75t
"""

# 1735 분수 합
def gcd(a,b):
    while a:
        r = b%a
        a, b = r, a
    
    return b

n1, n2 = map(int, input().split())
m1, m2 = map(int, input().split())

new_1 = (n1*m2) + (m1*n2) # 분자
new_2 = n2*m2 # 분모

new_gcd = gcd(new_1, new_2)
print(new_1//new_gcd, new_2//new_gcd)