# -*- coding: utf-8 -*-
"""# 3058

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ja3wbib429kn-nygRxe6cboGJMW9G3qM
"""

# 3058 짝수를 찾아라
import sys
T = int(input()) # 테스트 케이스

for i in range(T):
    even = [x for x in list(map(int, sys.stdin.readline().split())) if x % 2 == 0] # 리스트를 입력받고 짝수만 추출

    print(sum(even), min(even))