# -*- coding: utf-8 -*-
"""# 7287

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H8fuJIXIpZ-MCBGq3Dh-9BCMxcf_K9RL
"""

# 7287 등록
print(121)
print('mpq05')