# -*- coding: utf-8 -*-
"""# 14501

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qenuVrzR_Oa2L1KHBgk4badPRMUybsB-
"""

# 14501 퇴사
import sys
N = int(input())
dp = [0 for _ in range(N+1)]
T = []
P = []

for _ in range(N):
    t, p = map(int, sys.stdin.readline().split())
    T.append(t)
    P.append(p)

for i in range(N-1, -1, -1):
    if N < T[i] + i:
        dp[i] = dp[i+1]
    else:
        dp[i] = max(dp[i+1], dp[i+T[i]] + P[i])
    
print(dp[0])