# -*- coding: utf-8 -*-
"""# 16435

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Wm7k_5aEDIL-kdGxXlgODk4zvehTy9M
"""

# 16435 스네이크버드
N, L = map(int, input().split())
h = list(map(int, input().split())) 

h.sort()

for i in range(N):
    if L >= h[i]:
        L += 1
    else:
        break
print(L)