# -*- coding: utf-8 -*-
"""# 9012

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1p3ShJ1JF_uulvqtyQh4Jz6PVSBoZie
"""

# 9012
T = int(input())

for i in range(T):
    sent = input()
    sent = list(sent)
    count = 0

    for i in sent:
        if i == '(':
            count += 1
        elif i == ')':
            count -= 1
            
        if count < 0:
            print('NO')
            break;

    if count > 0:
        print('NO')
    elif count == 0:
        print('YES')