# -*- coding: utf-8 -*-
"""# 2193

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ac0R4_DfvOpewCZkA0aCQEgZ4Frjc3Bk
"""

# 2193 이친수

a = [1, 1]

for i in range(2, 91):
  a.append(a[i - 2] + a[i - 1])

n = int(input())

print(a[n-1])