# -*- coding: utf-8 -*-
"""# 11943

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QBtYk3OlcWPWxE7Gqmrq8QSpYIjZ5tKr
"""

# 11943 파일 옮기기
A, B = map(int, input().split())
C, D = map(int, input().split())

if A + D < C + B:
    print(A + D)
else:
    print(C + B)