# -*- coding: utf-8 -*-
"""# 2217

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWzUdCTRkepZP3w9vkvm10tRBMqXDtiD
"""

# 2217 로프
import sys
N = int(input())
rope = []

for i in range(N):
    rope.append(int(sys.stdin.readline()))

rope.sort()

for i in range(N):
    rope[i] = rope[i] * (N-i)

print(max(rope))