# -*- coding: utf-8 -*-
"""# 11022

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JRoPxnTAmsTJI_kG6SPDelMO2KQzpx2
"""

# 11022 A+B-8
T = int(input())
for i in range(T):
    A, B = map(int, input().split())
    # "Case #x: A + B = C" 형식
    print(f'Case #{i+1}: {A} + {B} = {A+B}')