# -*- coding: utf-8 -*-
"""# 15596

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnLdvT0APG_aeJvXGVchX7SNoWGdoTi-
"""

# 15596 정수 N개의 합
def solve(a):
    sum = 0
    for i in a:
        sum += i

    return sum