# -*- coding: utf-8 -*-
"""# 17413

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ICZsdAwoAvKbPwBxWH4TlcSY79DCNZi
"""

# 17413 단어 뒤집기 2
S = list(input())
tag = False
word = ''
reverse = ''

for i in S:
    if tag == False:
        if i == '<':
            tag = True
            word = word + i
        elif i == ' ':
            word = word + i
            reverse = reverse + word
            word = ''
        else:
            word = i + word
    elif tag == True:
        word = word + i
        if i == '>':
            tag = False
            reverse = reverse + word
            word = ''

print(reverse + word)