# -*- coding: utf-8 -*-
"""# 17413

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ICZsdAwoAvKbPwBxWH4TlcSY79DCNZi
"""

# 17413 단어 뒤집기 2
a=input().replace('>','<').split('<')
s=""
for i in range(len(a)):
  if i%2:
      s+='<'+a[i]+'>'
  else:
    c=a[i].split()
    s+=' '.join([d[::-1] for d in c])
print(s)