# -*- coding: utf-8 -*-
"""# 6679

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdaxCPoURB7EwmzZ9Az-29aS2aEaazib
"""

# 6679 싱기한 네자리 숫자

def numerical(a, b):
    sum = 0
    while a > 0:
        sum += a % b
        a = a // b
    return sum

for i in range(1000, 10000):
    if numerical(i,10) == numerical(i, 12) and numerical(i,10) == numerical(i, 16):
        print(i)