# -*- coding: utf-8 -*-
"""# 4949

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kWJG_1wPxNnKoRO3WwDCvk5DskB4zqZb
"""

# 4949 균형잡힌 세상
import sys
while True:
    n = sys.stdin.readline().rstrip()
    stack = []
    equal = True

    if n == '.':
        break

    for i in n:
        if i =='(' or i == '[':
            stack.append(i)
        elif i == ')':
            if not stack or stack[-1] == '[':
                equal = False
                break
            elif stack[-1] == '(':
                stack.pop()
        elif i == ']':
            if not stack or stack[-1] == '(':
                equal = False
                break
            elif stack[-1] == '[':
                stack.pop()
    
    if equal == True and not stack:
        print('yes')
    else:
        print('no')