# -*- coding: utf-8 -*-
"""# 1912

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_d3O_cyf8ujbDsBwlf8PD2ZfTbFSkBx
"""

# 1912 연속합
n = int(input())
seq = list(map(int, input().split()))

dp = [0 for _ in range(n)]

for i in range(n):
    dp[i] = max(dp[i-1] + seq[i], seq[i])
    
print(max(dp))