# -*- coding: utf-8 -*-
"""# 2231

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wMVsQiIt54M-9m6HQ6-N_OA67xzM5kTt
"""

# 2231 분해합

N = int(input())
temp = 0
for i in range(1,N):
    M = i
    for j in (str(i)):
        M += int(j)
    
    if N==M:
        temp = 1
        print(i)
        break

if temp == 0:
    print(0)