# -*- coding: utf-8 -*-
"""# 2163

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FeKhl_AU4qel3FNjojUGzBAl7xAQbMFs
"""

# 2163 초콜릿 자르기
N, M = map(int, input().split())
print(N*M-1)