# -*- coding: utf-8 -*-
"""# 11651

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_k6CfIo7q0ebSpWSVZfcpxqDug9EuqPF
"""

# 11651 좌표 정렬
import sys
N = int(input())
nums = []

for _  in range(N):
    x, y = map(int, sys.stdin.readline().split())
    nums.append((x,y))

sorted_nums = sorted(nums, key = lambda x: (x[1], x[0]))

for i in range(N):
    print(sorted_nums[i][0], sorted_nums[i][1])