# -*- coding: utf-8 -*-
"""# 1181

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aiknkS_BR7C8Bg6Q48xTvEGBLuhfp_mB
"""

# 1181 단어 정렬
import sys
N = int(input()) # 단어의 개수
word_list = set() # set으로 단어 리스트를 만들어 줄 것

for _ in range(N):
    word_list.add(sys.stdin.readline())

# set은 순서가 없고, 인덱스가 없으므로
word_list = list(word_list) # 리스트로 바꿔준다
word_list.sort() # 알파벳 순으로 정렬
word_list.sort(key=len) # 알파벳 순으로 정렬된 상태로 길이 정렬

print(''.join(word_list))