# -*- coding: utf-8 -*-
"""# 1157

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XT3LtqsnxtRl95sFHsn3Ge5qCT9VzcE7
"""

# 1157 단어 공부

alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
check = [0] * 26

word = input().upper() # 입력받은 문자를 대문자로 바꿔준다.

for i in range(len(word)):
    check[alphabet.index(word[i])] += 1

index = check.index(max(check)) # 가장 많이 나오는 첫 알파벳의 인덱스 저장
double = False

for i in range(index+1, 26):
    if check[i] == check[index]:
        double = True
        break;

if double == True:
    print('?')
else:
    print(alphabet[index])