# -*- coding: utf-8 -*-
"""# 5347

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAkvxO2-mVC4OEq1Z9GyDtqH7wOOe2_0
"""

# 5347 LCM
import sys
def gcd(a,b):
    while a:
        r = b%a
        a, b = r, a

    return b

N = int(input())

for _ in range(N):
    a, b = map(int, sys.stdin.readline().split())
    div = gcd(a,b)

    print(a*b//div)