# -*- coding: utf-8 -*-
"""# 2108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmKCyjS_UelLy0-UAZ1br9H9-zUxY47H
"""

# 2108 통계학
from collections import Counter
N = int(input())
nums = []
nums_dict = {}

for i in range(N):
    num = int(input())
    nums.append(num)

nums.sort() # 기본 정렬
many_nums = Counter(nums).most_common() # 빈도 수를 기준으로 정렬 후 튜플로 반환

most = many_nums[0][0] 
if N > 1: 
    if many_nums[0][1] == many_nums[1][1]: # 최빈값이 여러개일 때를 대비
        most = many_nums[1][0]

print(round(sum(nums) / N)) # 산술평균
print(nums[N//2])
print(most) # 최빈값
print(nums[-1] - nums[0]) # 범위