# -*- coding: utf-8 -*-
"""# 9613

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10RGRsOqsRsfHYvPyMQ3UTVzTZQ1utCVo
"""

# 9613 GCD 합
def gcd(a, b): # 최대 공약수, 양의 정수만 입력이므로 a,b < 0 고려 X
    while b>0:
        r = a%b
        a = b
        b = r
    return a

t = int(input()) # 테스트 케이스
for i in range(t):
    num = list(map(int, input().split()))
    n = num.pop(0) # 첫번째 입력은 수의 개수 n

    gcd_sum = 0
    for j in range(n):
        for k in range(j+1,n):
            gcd_sum += gcd(num[j],num[k])
    print(gcd_sum)