# -*- coding: utf-8 -*-
"""# 2581

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hZYS0BWW0iyHa04cdXoEqi1ZDXJFQuu
"""

# 2581 소수
def is_prime(n):
    if n == 1:
        return False
        
    for i in range(2, int(n**0.5) + 1):
        if n%i == 0:
            return False
    return True

primes = []

M = int(input())
N = int(input())

for i in range(M, N+1):
    if is_prime(i):
        primes.append(i)

if primes:
    print(sum(primes))
    print(primes[0])
else:
    print(-1)