# -*- coding: utf-8 -*-
"""# 2309

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIVbm1WH8y4q2a_fNIaCPY8tbCPs7ElO
"""

# 2309 일곱 난쟁이
hats = []
hundred = False

for i in range(9):
    hats.append(int(input()))

for i in range(8):
    if hundred:
        break

    for j in range(i+1,9):
        if sum(hats) - (hats[i] + hats[j]) == 100:
            hats.pop(i)
            hats.pop(j-1)
            hundred = True
            break
hats.sort()
for k in hats:
    print(k)