# -*- coding: utf-8 -*-
"""# 23841

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gi11lDMWiRSIpQd506oAKy1nV8BEfFC4
"""

# 23841 데칼코마니
N, M = map(int, input().split())

art = []
for i in range(N):
    art = list(input())
    for j in range(M):
        if art[j] != '.':
            art[M-j-1] = art[j]
    print(''.join(art))