# -*- coding: utf-8 -*-
"""# 11655

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rbl2_6ABR1KKiXMeui51yP4Ac48pvS4-
"""

# 11655 ROT13
S = input()

new_S = ""
for i in range(len(S)):
    ascii = ord(S[i])

    if ascii >= 65 and ascii <= 90:
        ascii += 13
        if ascii > 90:
            ascii %= 91 
            ascii += 65
    elif ascii >= 97 and ascii <= 122:
        ascii += 13
        if ascii > 122:
            ascii %= 123
            ascii += 97
    else:
        pass

    new_S += chr(ascii)

print(new_S)