# -*- coding: utf-8 -*-
"""# 2559

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gV3nl8hHTFhLrNPsrPt3nmixLrFQR40H
"""

# 2559 수열
N, K = map(int, input().split())
C = list(map(int, input().split()))
cur = sum(C[:K]) # 현재 부분합
high = cur # 가장 큰 부분합

for i in range(K, N):
    cur = cur - C[i-K] + C[i]
    high = max(high, cur)
    
print(high)