# -*- coding: utf-8 -*-
"""# 13706

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKvXcQjclcAeR-oWtY4ANwaGoCSANUg8
"""

# 13706 제곱근
 
def Binary_Search(left, right): # 이진 탐색
    target = right

    while (left <= right):
        mid = (left + right) // 2
        if (mid ** 2) == target:
            return mid
        elif mid ** 2 < target:
            left = mid 
        elif mid ** 2 > target:
            right = mid
    return -1

N = int(input())
result = Binary_Search(1,N)
print(result)