# -*- coding: utf-8 -*-
"""# 23327

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ny5De3jThBpzeycWMD0UaUTfMHU-JdiZ
"""

# 23327 리그전 오브 레전드
import sys

N, Q = map(int, input().split())
L = map(int, input().split())

t1 = [0]
t2 = [0]

for i in (L):
    t1.append(t1[-1] + i)
    t2.append(t2[-1] + i**2)

for _ in range(Q) :
    l, r = map(int, sys.stdin.readline().split())
    s1 = t1[r] - t1[l-1]
    s2 = t2[r] - t2[l-1]
    score = (s1**2 - s2) // 2
    print(score)