# -*- coding: utf-8 -*-
"""# 1758

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0RCa7Zl9cAWiG04OoQSVOqMEVVWHuUn
"""

# 1758 알바생 강호
import sys
def get_tip(m, t):
    # m = 원래 주려고 한 돈
    # t = 받은 등수
    tip = m - (t - 1)

    if tip <= 0:
        return 0
    else:
        return tip

N = int(input())        
tips = [int(sys.stdin.readline()) for _ in range(N)]
tips.sort(reverse=True)

max_tip = 0
for i in range(N):
    m = tips[i]
    t = i+1
    max_tip += get_tip(m, t)

print(max_tip)