# -*- coding: utf-8 -*-
"""# 1764

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJSShkxleTFl-TRRfInmeUEP1Kn0Y31j
"""

# 1764 듣보잡
import sys
N, M = map(int, input().split()) # 듣도 못한 사람의 수 N, 보도 못한 사람의 수 M
unheard = [] # 듣도 못한 사람
unseen = [] # 듣도 보도 못한 사람

for _ in range(N):
    name = sys.stdin.readline().rstrip()
    unheard.append(name)

for _ in range(M):
    name = sys.stdin.readline().rstrip()
    unseen.append(name)

# 집합 자료형 사용 => 교집합
result = list(set(unheard) & set(unseen)) # 다시 리스트로 바꿔서 정렬할 예정
result.sort() # 사전순으로 정렬

print(len(result))
for name in result:
    print(name)