# -*- coding: utf-8 -*-
"""# 2475

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Lo22Ji7vsgGH0vkYVPSADot2Qi0amUr
"""

# 2475 검증수

nums = list(map(int, input().split()))

sum = 0
for i in nums:
    sum += i ** 2

print(sum%10)