# -*- coding: utf-8 -*-
"""# 14921

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTAK4jcSq2x-0lu1cUaLGZVAD8mYUrNu
"""

# 14921 용액 합성하기
N = int(input())
value = list(map(int, input().split()))

# initialization
start, end = 0, N-1
threshold = 2000000001

# Solution
while start < end:
    sumValue = value[start] + value[end]
    absSum = abs(sumValue)

    if absSum < threshold: # 0에 더 가까우면
        threshold = absSum # 저장
        ans = sumValue

    if sumValue < 0: # 0보다 작으면
        start += 1 # 값 키워보자
    else:
        end -= 1

print(ans)