# -*- coding: utf-8 -*-
"""# 9933

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAJdMUemTicTU7pnjo7vtSjt154mW-GF
"""

# 9933 민균이의 비밀번호
N = int(input())

word_list = [] # 단어를 담을 리스트
check = 0

for i in range(N):
    word_list.append(input())

for j in range(N):
    flipped_word = word_list[j][::-1] # j번째 단어 뒤집기
    for k in word_list:
        if flipped_word == k:
            password = word_list[j]
            check = 1    
            break
    if check == 1:
        break

length = len(password)
mid = length // 2

print(length, password[mid])