# -*- coding: utf-8 -*-
"""# 1149

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Isb_K1toyIrig5QkukCmp2IsilsChXW_
"""

# 1149 RGB거리
import sys
N = int(input())
W = [] # 색 별 가중치

for _ in range(N):
    W.append(list(map(int, sys.stdin.readline().split())))

for i in range(1, N): # i번째 색을 칠할 때 i-1번이랑 색을 다르게 칠하면 됨.
    # i-1 번째 집에 칠할 수 있는 색 중 더 값이 작은 색으로 칠하면 된다.
    W[i][0] = min(W[i-1][1], W[i-1][2]) + W[i][0]
    W[i][1] = min(W[i-1][0], W[i-1][2]) + W[i][1]
    W[i][2] = min(W[i-1][0], W[i-1][1]) + W[i][2]

print(min(W[N-1])) # 최종 칠해진 세가지 케이스 중 가장 작은 값 출력