# -*- coding: utf-8 -*-
"""# 11726

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GoT5opR3za39s_iedQM_tIBBm93GCCw5
"""

# 11726 2 x n 타일링
n = int(input())

n_1 = 1
n_2 = 1

for i in range(2,n+1):
    n_2, n_1 = (n_1 + n_2) % 10007, n_2 % 10007

print(n_2)