# -*- coding: utf-8 -*-
"""#8393

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eoR5YOHqxed1rOXPOaVbRZ89H0-rU13e
"""

# 8393 합1

n = int(input())
sum = 0

for i in range(1,n+1):
    sum = sum + i

print(sum)

# 8393 합2

n = int(input())

print((n**2+n)//2)