# -*- coding: utf-8 -*-
"""# 11000

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQy5s7a-dEWqfHTXNXQwcy-p1FqBdaIA
"""

# 11000 강의실 배정
import heapq
import sys
input = sys.stdin.readline
N = int(input())
queue = []
classRoom = []

for _ in range(N):
    S, T = map(int, input().split())
    queue.append((S, T))

queue.sort()
heapq.heappush(classRoom, queue[0][1]) # 끝나는 시간

for i in range(1, N):
    if queue[i][0] < classRoom[0]: # 강의 끝나는 시간보다 시작 시간이 빠른 경우
        heapq.heappush(classRoom, queue[i][1]) # 강의 끝나는 시간 추가
    else: 
        heapq.heappop(classRoom) # 그대로 빼주고
        heapq.heappush(classRoom, queue[i][1]) # 끝나는 시간만 업데이트 해줌
        
print(len(classRoom))