# -*- coding: utf-8 -*-
"""# 23056

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y743zaZSlzC8FUFleFjKKf6nMokkNhg-
"""

# 23056 참가자 명단
import sys

N, M = map(int, input().split())
white = [] # 백팀
blue = [] # 청팀
count = [0 for _ in range(N+1)]

while True:
    num, name = sys.stdin.readline().rstrip().split()
    #num, name = input().split()
    if num == '0' and name == '0':
        break

    if count[int(num)] < M:
        count[int(num)] += 1
    
        color = int(num) % 2

        if color == 1:
            blue.append((num, name))
        else:
            white.append((num, name))

    
 

white.sort(key = lambda x:(int(x[0]), len(x[1]), x[1])) 
blue.sort(key = lambda x:(int(x[0]), len(x[1]), x[1]))

for i, j in blue:
    print(i, j)

for i, j in white:
    print(i, j)