# -*- coding: utf-8 -*-
"""# 10610

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-MrLFgHYT7HNr5uDrZpnDxPRhGJBzC8
"""

# 10610 30
N = list(input())
N.sort(reverse=True)

sum = 0
for i in N:
    sum += int(i)

if sum % 3 != 0:
    print(-1)
elif N[-1] != '0':
    print(-1)
else:
    print("".join(N))