# -*- coding: utf-8 -*-
"""# 2352

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rl0dZ8gD4bDxlalGP6-513gFtUPvD91d
"""

# 2352 반도체 설계
n = int(input())
num = list(map(int, input().split()))
lis = [0]

for i in num:
    if lis[-1] < i:
        lis.append(i)
    else:
        start, end = 0, len(lis)
        while start < end:
            mid = (start+end) // 2
            if lis[mid] < i:
                start = mid+1
            else:
                end = mid
        lis[end] = i

print(len(lis)-1)