# -*- coding: utf-8 -*-
"""# 1920

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m2IXKDcyBNbC0dceidI7lAZD2YVyBeI1
"""

# 1920 수 찾기
N = int(input())
A = list(map(int, input().split())) # N 개 만큼 입력
M = int(input())
find = list(map(int, input().split())) # M 개 만큼 입력
A.sort() # 이분 탐색을 위해 정렬

for i in find: # target = i
    left = 0
    right = N

    while left<=right:
        mid = (left + right) // 2

        if mid < N and mid > -1:
            if A[mid] < i:
                left = mid + 1
            else:
                right = mid - 1
        else:
            break

    if mid < N and mid > -1:
        if i == A[right + 1]:
            print(1)
        else:
            print(0)
    else:
        print(0)