# -*- coding: utf-8 -*-
"""# 2156

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DkhZpyGl5YLQTkL5avKPkSZzo4iSRtiJ
"""

# 2156 포도주 시식
import sys
n = int(input())
amounts = [0] # amounts[0]
dp = [0] # dp[0]

for _ in range(n):
    amounts.append(int(sys.stdin.readline())) # amounts[1] ~ amounts[n]

dp.append(amounts[1]) # dp[1]
if n > 1:
    dp.append(amounts[1] + amounts[2]) # dp[2]
for i in range(3, n+1):
    dp.append( max(dp[i-1], dp[i-3] + amounts[i-1] + amounts[i], dp[i-2] + amounts[i]) )

print(dp[n])