# -*- coding: utf-8 -*-
"""# 1059

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFPTsgWv60Py34suHLsV6mc3GCRVcK9n
"""

# 1059 좋은 구간
L = int(input()) # 집합 S의 크기
S = [0] + sorted(list(map(int, input().split())))
n = int(input())
A = 0
B = 0

if n in S:
    print(0)
else:
    for i in S:
        if n > i:
            A = i + 1
        else:
            B = i - 1
            break
    print( B-A + (B-n)*(n-A) )