# -*- coding: utf-8 -*-
"""# 9576

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqbgh5y6uehDKFCgqOUnW6h1wT57Uqui
"""

# 9576 책 나눠주기
from collections import deque
import sys
input = sys.stdin.readline

T = int(input())

for _ in range(T):
    N, M = map(int, input().split())
    books = [0 for _ in range(N+1)]
    want = []
    cnt = 0

    for _ in range(M):
        a, b = map(int, input().split())
        want.append((a,b))

    want.sort(key = lambda x:x[1])
    want = deque(want)
    while want:
        a, b = want.popleft()

        for i in range(a, b+1):
            if not books[i]:
                cnt += 1
                books[i] = 1
                break
    print(cnt)