# -*- coding: utf-8 -*-
"""# 2109

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11a0dk7SZ0iB0PsjzXm6QvTqcWjzQ2MlH
"""

# 2109 순회강연
n = int(input())
request = []
pay = [0 for _ in range(10001)]

for _ in range(n):
    p, d = map(int, input().split())
    request.append((p, d))

request.sort(reverse=True)

for i in range(n):
    idx = request[i][1]

    while idx:
        if not pay[idx]:
            pay[idx] = request[i][0]
            break
        idx -= 1

print(sum(pay))