# -*- coding: utf-8 -*-
"""# 10844

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zAyDkI2nSHkoGl68doKw5oKWOj-sBLQ7
"""

# 10844 쉬운 계단 수

N = int(input()) # 수의 길이

# [길이][마지막 수]
dp = [[0 for i in range(11)] for j in range(101)]

for i in range(1, 10):
    dp[1][i] = 1 # 길이가 1, 마지막 수에 상관없이 모두 1

for i in range(2, N + 1):
    dp[i][0] = dp[i-1][1]

    for j in range(1, 10):
        dp[i][j] = (dp[i - 1][j - 1] + dp[i - 1][j + 1])

sum = 0
for i in range(10):
    sum += dp[N][i];

print(sum % 1000000000)