# -*- coding: utf-8 -*-
"""# 20113

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AyV7Dms8axEu0tzT8tECBqpzjvFXtK04
"""

# 20113 긴급 회의
N = int(input())

player_list = [0 for _ in range(N)] # 플레이어 마다 투표를 받을 빈 리스트

vote_list = list(map(int, input().split()))

pass_count = 0 # 건너뛴 수

for i in vote_list:
    if i == 0: # 0을 투표했으면 건너뛰기
        pass_count += 1
        continue
    player_list[i-1] += 1

imposter = player_list.index(max(player_list)) # 임포스터의 인덱스 저장
player_list.sort(reverse=True) # 투표 받은 수를 내림차순으로 정렬 


if player_list[0] == player_list[1]: # 가장 많은 투표를 받은 사람이 최소 두명 이상
    print("skipped")
else:
    print(imposter+1) # index 이므로 + 1