# -*- coding: utf-8 -*-
"""# 2292

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yePGzYoSd5KRnpOksof_BC2Ghhkli2jR
"""

# 2292 벌집
# 1 7 19 37 61 각 층의 기준
#  6 12 18 24 증가 기준
N = int(input())
count = 1
temp_num = 1 # 기준이 되는 수 1 7 19 37 ~
n = 1 # 6의 증가범위를 설정해줄 수 
while 1:
    if N > temp_num:
        count += 1
        temp_num += n*6
        n += 1
    else:
        break;
print(count)