# -*- coding: utf-8 -*-
"""# 2312

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15a-bUmeJw27xzIyn9ywLN9O2V69WpMKn
"""

# 2312 수 복원하기
N = int(input())

for _ in range(N):
    num = int(input())
    div = 2

    while num > 1:
        cnt = 0

        if num % div == 0:
            while num % div == 0:   
                num //= div
                cnt += 1
            print(div, cnt)

        elif div > num**0.5: # 제곱근 이상부터는 확인할 필요 x
            print(num, 1)
            break

        div += 1   # 다음 인수