# -*- coding: utf-8 -*-
"""# 20920

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13bSe-ycnjyd6enZL6j4xWjX9RKJzs4Nb
"""

from collections import Counter
import sys

N, M = map(int, input().split())
words = []

for i in range(N):
    word = sys.stdin.readline().rstrip()
    if len(word) >= M:
        words.append(word)
        
counts = Counter(word for word in words)
words = sorted(counts)
words.sort(key=len, reverse=True)
words.sort(key=counts.__getitem__, reverse=True)


for w in words:
    print(w)