# -*- coding: utf-8 -*-
"""#2675

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zg1mqgA9ekgc0HQBHVerxp6XGao_6n7U
"""

#2675 문자열 반복
T = int(input()) # 테스트 케이스의 개수

for i in range(T):
    R, S = input().split()
    P = '' # P 테스트 케이스마다 새 문자열을 만들어준다.
    for i in S:
        P += int(R)*i # i+1번째 문자를 R번 반복하게 추가.
    print(P)