# -*- coding: utf-8 -*-
"""# 18247

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6MsEMBsfPkZzsxKoloa47xulJnFZjlM
"""

# 18247 겨울왕국 티켓 예매
T = int(input())
 
for _ in range(T):
    N, M = map(int,input().split()) # N => 영화관 자리 열 수, M => 한 열에 속한 좌석 개수

    if N <12 or M<4:
        print(-1)
    else:
        print(11*M + 4)