# -*- coding: utf-8 -*-
"""# 1725

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQrmiht_pMFPqOfmqC1oByNwM8m2yIRW
"""

# 1725 히스토그램
import sys

N = int(input())
area = 0
height = [] # 각 자리의 높이 저장
stack = [] # 위치 값을 저장

for i in range(N):
    height.append(int(sys.stdin.readline()))
    while (stack and height[stack[-1]] > height [i]): # stack이 비지 않고, 입력 높이가 이 전의 높이보다 작으면
        j = stack[-1]
        stack.pop()
        width = i
        
        if stack:
            width -= stack[-1] + 1
        
        result = height[j] * width
        if area < result:
            area = result

    stack.append(i) # 위치 값 저장

while len(stack) != 0:
    j = stack[-1]
    stack.pop()
    width = N
        
    if stack:
        width -= stack[-1] + 1

    result = height[j] * width
    if area < result:
        area = result

print(area)