# -*- coding: utf-8 -*-
"""# 8949

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SQiE31GC-idHYErF05ZLCsGiFFkoTqKE
"""

# 8949 대충 더해
A, B = map(int,input().split())
ans = ""
while A or B:
    ans = str(A%10 + B%10) + ans
    A, B = A//10, B//10

print(ans)