# -*- coding: utf-8 -*-
"""# 1305

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ojMWBJtr16a4KhZmQqE-xP4ZJJJW2Z5n
"""

# 1305 광고
L = int(input()) # 광고판의 크기
s = input() # 광고판에 보이는 문자열

# 실패함수 
failure=[0 for _ in range(L)] # 실패함수 값을 담을 리스트
j = 0
for i in range(1,L):
    while j>0 and s[i]!=s[j]:
        j = failure[j-1]
   
    if s[i]==s[j]:
        j += 1
        failure[i] = j
 
add_len = L - failure[-1] # 가장 짧은 광고 길이
print(add_len)