# -*- coding: utf-8 -*-
"""# 11650

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lK03Ub3mRpHe1brnhTBOHXZBlXaCh-Ls
"""

# 11650 좌표 정렬하기 => 리스트 안에 요소로 리스트 넣기
N = int(input())
# x와 y를 한번에 담을 리스트 생성
XandY = []

for i in range(N):
    XandY.append(list(map(int, input().split())))

XandY = sorted(XandY) # 정렬

for i in XandY:
    print(i[0], i[1])