# -*- coding: utf-8 -*-
"""# 1037

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkM3UnZisHVhIfvFLq74DFhKNgO_ecpK
"""

# 1037 약수
num = int(input())
devisors = sorted(list(map(int,input().split())))

print(devisors[0] * devisors[num-1])