# -*- coding: utf-8 -*-
"""# 10988

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVY7ZDogEhQfzl5luuiFdyNBx2s2n6dh
"""

# 10988 팰린드롬인지 확인하기
word = input()
reversed_word = word[::-1]

if word == reversed_word:
    print(1)
else:
    print(0)