# -*- coding: utf-8 -*-
"""# 13199

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11bMUWVrLpdYTkNaM_UdrF1iE421RSalO
"""

# 13199 치킨 먹고 싶다
import sys
T = int(input()) # 테스트 케이스의 개수

for i in range(T):
    # 치킨의 가격, 치킨에 쓸 돈, 공짜로 시킬 때 필요한 쿠폰 수, 시키면 주는 쿠폰 수
    P, M, F, C = map(int, sys.stdin.readline().split()) 

    coupon = (M // P) * C # 둘 다 얻을 수 있는 쿠폰 수
    normal_cnt = (M // P) + coupon // F # 단골 아닐 때 치킨 수
    cnt = M // P # 단골 기준 치킨 수
    
    # 단골 기준 쿠폰이 필요한 쿠폰 수 보다 많다면
    if (coupon >= F):
        cnt += 1 + (coupon - F) // (F-C) 

    print(cnt - normal_cnt)