# -*- coding: utf-8 -*-
"""#16561

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/144vyJ2Un3VmCEGAhTNmaikz5mdT9DFdv
"""

#16561 3의 배수
N = int(input())

Ndiv3 = N // 3
case =  ( (Ndiv3-2)*(Ndiv3-1) ) // 2

print(case)