# -*- coding: utf-8 -*-
"""# 1057

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HWW-7MYJybg76nmb1_06AHv2NgmuW873
"""

# 1057 토너먼트
N, Kim, Lim = map(int, input().split())
cnt = 0

while Kim != Lim: # 둘이 같은 번호가 될 수는 없음. 
# 둘이 만나서 이기면 똑같은 번호가 되겠지?
    Kim -= Kim // 2
    Lim -= Lim // 2
    cnt += 1
    
print(cnt)