# -*- coding: utf-8 -*-
"""# 10214

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w68nJFOY24lZ6ji--8BnQEPyfUUj_Oy8
"""

# 10214 Baseball
import sys
T = int(input())

for i in range(T):
    # 테스트 케이스마다 각 팀의 점수 초기화
    Yonsei = 0
    Korea = 0
    for j in range(9):
        #Y, K = map(int, input().split())
        Y, K = map(int, sys.stdin.readline().split())
        Yonsei += Y
        Korea += K
    
    if Yonsei > Korea :
        print('Yonsei')
    elif Yonsei == Korea:
        print('Draw')
    else:
        print("Korea")