# -*- coding: utf-8 -*-
"""# 16122

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HWwAo5hJfXPGNwAkukgnZLRfem31atp_
"""

# 16122 Unary
N, M = map(int, input().split())
mod = 998244353

d = [0 for _ in range(1010101)]
l = [0 for _ in range(303030)]
r = [0 for _ in range(303030)]

d[0] = 1

def pw(a, b):
    ret = 1

    while b:
        if (b & 1):
            ret = ret * a % mod

        b >>= 1
        a = a * a % mod

    return ret

for i in range(1, 1010101):
    d[i] = d[i-1] * i % mod

for i in range(1, 303030):
    l[i] = min( (-1)*l[i-1], (-1)*l[i-1]-1, (-1)*r[i-1], (-1)*r[i-1]-1 )
    r[i] = max( (-1)*l[i-1], (-1)*l[i-1]-1, (-1)*r[i-1], (-1)*r[i-1]-1 )

if (M < l[N] or r[N] < M):
    print(0)
else:
    M -= l[N]
    print(d[N] * pw(d[M], mod-2) % mod * pw(d[N-M], mod-2) % mod)