# -*- coding: utf-8 -*-
"""# 1904

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19IWjn23JI7bLGEY47LjYqgriSJKStGCe
"""

# 1904 01타일
N=int(input())
ary = [0] * 1000001
ary[1], ary[2] = 1, 2

for i in range(3,N+1):
    ary[i] = (ary[i-1]+ary[i-2])%15746

print(ary[N])