# -*- coding: utf-8 -*-
"""# 21194

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5bI1FoRbUXeDjTnIbJJujG1s4C7_db5
"""

# 21194 Meditation
import sys
N, K = map(int, input().split())
score_list = []
maximal_sum = 0

for i in range(N):
    score_list.append(int(sys.stdin.readline()))

score_list.sort(reverse=True)

for j in range(K):
    maximal_sum += score_list[j]

print(maximal_sum)