# -*- coding: utf-8 -*-
"""# 11055

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYqKraD4DBkJUUPa_ZLRpMG8JtANJqLo
"""

# 11055 가장 큰 증가하는 부분 수열
N = int(input())
A = list(map(int, input().split()))
dp = A[:]

for i in range(1,N):
    for j in range(i):
        if A[i] > A[j]:
            dp[i] = max(dp[i], dp[j] + A[i])

print(max(dp))