# -*- coding: utf-8 -*-
"""# 1026

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13TLqHM4qGq15xqYUydLgaH80DReygS8v
"""

# 1026 보물
N = int(input())
A = list(map(int, input().split()))
B = list(map(int, input().split()))

A.sort()
B.sort(reverse=True)

sum = 0
for i in range(N):
    sum += A[i] * B[i]

print(sum)