# -*- coding: utf-8 -*-
"""#11399

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16GDRUb4ouBUem4TBYImsuzn8CtvH9ZUl
"""

# 11399 ATM

N = int(input())
P = list(map(int, input().split()))
P.sort()

P_i = 0 # i번째 사람이 걸리는 시간
sum = 0 # 시간의 총 합

for i in P:
    P_i += i
    sum += P_i

print(sum)