# -*- coding: utf-8 -*-
"""# 11659

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PIpmguypZEBHMDrdJBKc8c0fUPwAYQpT
"""

# 11659 구간 합 구하기 4
import sys
N, M = map(int, input().split())
nums = list(map(int,input().split()))
prefix = [0]

for i in range(N):
    prefix.append(prefix[i]+nums[i])

for _ in range(M):
    start, end = map(int, sys.stdin.readline().split())

    if start == 1:
        print(prefix[end])
    else:
        print(prefix[end]-prefix[start-1])