# -*- coding: utf-8 -*-
"""# 10828

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-N6_RIYo0HL7PwcR_85xvT-kImtt37r_
"""

# 10828 스택
import sys
N = int(input())

stack = []
for i in range(N):
    command = sys.stdin.readline().split()

    if command[0] == 'push':
        stack.append(command[1])

    elif command[0] == 'pop':
        if not stack:
            print(-1)
        else:
            a = stack.pop()
            print(a)
    elif command[0] == 'size':
        print(len(stack))
    elif command[0] == 'empty':
        if not stack:
            print(1)
        else:
            print(0)
    elif command[0] == 'top':
        if not stack:
            print(-1)
        else:
            print(stack[-1])