# -*- coding: utf-8 -*-
"""# 2743

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMTTrUvBLfC_FkG0t-tUi5nrtdvpJ_ix
"""

# 2743 단어 길이 재기

c = input()
print(len(c))