# -*- coding: utf-8 -*-
"""# 1965

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EMs2sBFq4dtVNHiKtyK7K0I9HNupMJXY
"""

# 1965, 상자 넣기
n = int(input())
box_list = list(map(int, input().split()))

dp = [1 for _ in range(n)]

for i in range(1,n):
    for j in range(i):
        if box_list[j] < box_list[i]:
            dp[i] = max(dp[i], dp[j]+1)

print(max(dp))