# -*- coding: utf-8 -*-
"""# 10174

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195s6tYCusX1XuPdABD0mGAMdquXuNluZ
"""

# 10174 팰린드롬
import sys

def is_p(s):
    s = s.lower()
    check_len = len(s) // 2

    for i in range(check_len):
        if s[i] != s[-(i+1)]:
            return 'No'
    return 'Yes'
    
n = int(input())

for _ in range(n):
    s = sys.stdin.readline().strip()
    print(is_p(s))