# -*- coding: utf-8 -*-
"""# 4344

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ySyaZfwRBh4HwIgytCRjTKnyT1jQcfA
"""

# 4344 평균은 넘겠지
C = int(input())

for i in range(C):
  N = list(map(int, input().split(' ')))
  avg = sum(N[1:]) / N[0]
  count = 0
  for j in N[1:]:
    if j > avg:
      count += 1
  
  print(str('%.3f'%round((count/N[0])*100, 3)) + '%')