# -*- coding: utf-8 -*-
"""# 2751

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kPEzCnq4ZsAGYRP4g-O27Rlfr9FwNc7_
"""

# 2751 수 정렬하기 2

N = int(input())
nums = []

for i in range(N):
    nums.append(int(input()))

nums = sorted(nums)

for j in range(N):
    print(nums[j])