# -*- coding: utf-8 -*-
"""#2741

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pLikrFoZEHcoJnDHza9EhBOiYIN39K47
"""

# 2741 N 찍기
N = int(input())

for i in range(N):
    print(i+1)