# -*- coding: utf-8 -*-
"""# 11727

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H75Cm8L12yVGmSJkt8wN1mqsiouGsHyp
"""

# 11727 2*n 타일링 2
# n=1, 1 // n = 2, 3 // n = 3, 5
n = int(input())
dp = [0, 1, 3 ,5]

for i in range(3, n):
    dp.append((dp[i-1]*2 + dp[i]) % 10007)

print(dp[n])