# -*- coding: utf-8 -*-
"""# 2960

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMi3Zl3DMt474Ilk7hG56C5tmgiCDb9T
"""

# 2960 에라토스테네스의 체
N, K = map(int,input().split())
nums = [x for x in range(2,N+1)] # 1. 2부터 N까지 모든 정수를 적는다.
del_nums = [] # 지워진 수를 담을 리스트

while nums != []:
    i = 1
    P = min(nums) # 아직 지우지 않은 수 중 가장 작은 수를 찾는다.
    while nums != []: # P를 지우고, 아직 지우지 않은 P의 배수를 크기 순서대로 지운다.
        if P*i > max(nums):
            break;
        if P*i in nums:
            del_nums.append(P*i)
            nums.remove(P*i)
        i += 1

print(del_nums[K-1])