# -*- coding: utf-8 -*-
"""# 11050

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qKH4QY79V8w8IdFWnQnbDW2f47qGDT5H
"""

# 11050 이항 계수 1
# nCk 
N, K = map(int, input().split())

def factorial(num):
    if num == 1 or num == 0:
        return 1
    elif num > 1:
        return num * factorial(num-1)

nCk = factorial(N) / (factorial(N-K) * factorial(K))

print("%d" %nCk)