# -*- coding: utf-8 -*-
"""# 1439

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNemgibQ_O1wER8epiS9LRpAyhPDO_5w
"""

# 1439 뒤집기
seq = input()
temp = '-1'
cnt = 0

for i in seq:
    if i != temp:
        temp = i
        cnt += 1

print(cnt//2)