# -*- coding: utf-8 -*-
"""# 2579

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JoQQU0HM7g0_qQ4K6lnZVQQ1FrHhTFON
"""

# 2579 계단 오르기
import sys
n = int(input()) # 계단 수

score = [0 for i in range(301)] # 계단 별 점수
dp = [0 for i in range(301)] # 다이나믹 프로그래밍으로 풀 예정

for i in range(n):
    score[i] = int(sys.stdin.readline())

# i번째 idx의 계단을 밟을 때 최대 점수
dp[0] = score[0] # 첫 계단
dp[1] = score[0] + score[1] # 두번째 계단 밟으면 반드시 첫 번째
dp[2] = max(score[1] + score[2], score[0] + score[2]) # 0, 1, 2 는 밟을 수 없다.

for i in range(3, n): # 경우의 수 두가지
    dp[i] = max(dp[i - 3] + score[i - 1] + score[i], dp[i - 2] + score[i])

print(dp[n - 1])