# -*- coding: utf-8 -*-
"""# 2455

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZp1y927igwPpxap4IzN33lkhxTdOoTY
"""

# 2455 지능형 기차

people = 0 # 사람 수를 기록할 변수
people_list = [] # 역 마다 사람 수를 담아두는 list

for i in range(4):
    off, on = map(int ,input().split())
    people += on - off # i+1번째 역에서 기차를 정차한 후 사람의 수

    if people > 10000:
        people = 10000
    people_list.append(people)

print(max(people_list))