# -*- coding: utf-8 -*-
"""# 2609

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMu59xPPC0m5hrcEXTElOpPhr-vQ88uM
"""

# 2609 최대공약수와 최대공배수

# 함수 만들기
def gcd(a,b):
    while b>0:
        r = a%b
        a = b
        b = r
    return a


def lcm(a,b):
    lcm = a*b // gcd(a,b)
    return lcm

# 입력
N, M = map(int, input().split())
# 출력
print(gcd(N,M))
print(lcm(N,M))