# -*- coding: utf-8 -*-
"""# 11047

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G7fR7lG6dnDPh5-VFMz8iEaAbNDNMVN5
"""

# 11047 동전 0

N, K = map(int, input().split())
coins = []
count = 0

for i in range(N):
    Ai = int(input())
    coins.append(Ai)

for j in range(N):
    if coins[N-1-j] <= K :
        count += K // coins[N-1-j]
        K %= coins[N-1-j]

print(count)