# -*- coding: utf-8 -*-
"""# 14909

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ezML_sVDf2w7QnhJxhdQ3u-8ahfKyAM
"""

# 14909 양수 개수 세기
a = list(map(int, input().split())) # 먼저 리스트로 입력받은 후
a = [i for i in a if i > 0] # 양의 정수만 남긴다. 
print(len(a))