# -*- coding: utf-8 -*-
"""# 1297

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TmUpkm6XPs3eSTMrv7-Mq1Mk40-E2s9z
"""

# 1297 TV크기

diag, height, width = map(int, input().split())

rate = diag / ((height**2 + width**2) ** 0.5)

print(int(rate * height), int(rate * width))