# -*- coding: utf-8 -*-
"""# 13277

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FXScMpD1UCzXoqTBWGylmUI-aHWC8l0V
"""

# 13277 큰 수 곱셈

A, B = map(int, input().split())
print(A*B)