# -*- coding: utf-8 -*-
"""# 9095

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KpnuBaMjj8_nqCUkR4dfbbHjPdJt60t
"""

# 9095 1, 2, 3 더하기

def solve(n):
    ary = [0, 1, 2, 4]

    for i in range(3,n):
        ary.append(ary[i] + ary[i-1] + ary[i-2])

    print(ary[n])
    

T = int(input()) # 테스트 케이스의 개수

for _ in range(T):
    n = int(input()) # 1 <= n < 11
    solve(n)