# -*- coding: utf-8 -*-
"""# 6378

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14G6ssyXq9jcUJCKJ68SBqoZ_FpLI_maf
"""

# 6378 디지털 루트
while 1: 
    N = int(input())
    if N == 0: # N은 0이면 실행 종료.
        break;
      
    while N > 9: # N이 한자리 수이면 자동으로 pass
        sum = 0 # 디지털 루트는 각 자리의 합이 한자리가 되야한다.
        for i in str(N):
            sum += int(i)
        N = sum # 각 자리의 합 => 만약 10이상(두자리 수 이상)이라면 다시 실행
    print(N)