# -*- coding: utf-8 -*-
"""# 1205

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8GwJlLOro9so1UGFEnTSuxi7S7LcqLy
"""

# 1205 등수 구하기

N, new, P = map(int, input().split())

if N == 0:
    print(1)
else:
    score = list(map(int,input().split()))
    score.append(new)

    score.sort(reverse=True)

    cont = 0
    for i in range(N+1):
        if score[i] == new:
            rank = i+1
            cont += 1

    if cont >= 2:
        real_rank = rank - (cont-1)
    else:
        real_rank = rank

    if rank <= P:
        print(real_rank)
    else:
        print(-1)