# -*- coding: utf-8 -*-
"""# 1748

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkYHmkpcggInZNWedl4M15ENoDLniGnM
"""

# 1748 수 이어 쓰기1

N = input()
num_len  = len(N) # 자리 수 계산
ans = 0

# 해당 자리 수 - 1 까지 만큼은 반복문으로 +
i = 0
while i< num_len - 1:
    ans += (i+1) * ( 9 * (10 ** i) )
    i += 1

ans += ( int(N) -  (10 ** i) + 1 ) * (i+1)

print(ans)