# -*- coding: utf-8 -*-
"""# 1699

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IJFBQjCcbZj6UEyyqdt5DW2xdhfTsN9
"""

# 1699 제곱수의 합
N = int(input())
dp = [0 for _ in range(N+1)]
s = [i**2 for i in range(1,317)] # 100000까지 제곱 수

for i in range(1, N+1):
    squares = []
    for square in s:
        if i < square:
            break
        squares.append(dp[i-square])
    dp[i] = min(squares) + 1

print(dp[N])