# -*- coding: utf-8 -*-
"""# 2417

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2DvFjOfbcpyh_FnCz36IaMeZAgxmBz3
"""

# 2417 정수 제곱근

N = int(input())

start, end = 0, N

while start <= end:
    mid = (start + end) // 2
    if mid ** 2 < N:
        start = mid + 1
    else:
        end = mid - 1

print(start)