# -*- coding: utf-8 -*-
"""# 1120

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yDPGk1Sn_9kRbFHcf3bpADcIJbDKaQ5a
"""

# 1120 문자열
X, Y = input().split()
min_dis = 50 # A와 B의 길이는 최대 50

for i in range(len(Y)-len(X)+1):
    cnt = 0
    for j in range(len(X)):
        if X[j] !=  Y[i+j]:
            cnt += 1
    if min_dis > cnt:
        min_dis = cnt 

print(min_dis)