# -*- coding: utf-8 -*-
"""# 5430

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIzJKQD8QXTiW-qgi4RvtT3k5ioKY02r
"""

# 5430 AC
import sys
T = int(sys.stdin.readline()) # ~100

for _ in range(T):
    p = sys.stdin.readline().rstrip()
    n = int(sys.stdin.readline())
    l = sys.stdin.readline().rstrip()[1:-1].split(',')
    p = p.replace('RR','') # 연속 두번 나오면 no 의미

    R_cnt = 0 # 뒤집는 횟수
    front = 0 # 앞에서부터 지우는 횟수
    end = 0 # 뒤에서부터 지우는 횟수

    for i in p:
        if i == 'R':
            R_cnt += 1 
        elif i == 'D':
            if R_cnt % 2 == 0: # 짝수 만큼 뒤집힌 경우 
                front += 1 # 앞 숫자 버리기
            else:
                end += 1 # 뒷 숫자 버리기

    if (front + end) <= n: # error가 아닌 case
        l = l[front:n-end]

        if R_cnt % 2 == 0: # 그대로 출력
            print(f'[{",".join(l)}]')
        else: # 뒤집어서 출력
            l.reverse()
            print(f'[{",".join(l)}]')
    else:
        print('error')