# -*- coding: utf-8 -*-
"""# 3053

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oUrxRvcvs6Qa-jvLPwMy4mpcE3QaY_4r
"""

# 3053 택시 기하학
R = int(input())
pi = 3.14159265358979

area1 = R * R * pi # 원 넓이
area2 = R * R * 2 # 택시 기하학 원 넓이
print(f"{area1:.6f}")
print(f"{area2:.6f}")