# -*- coding: utf-8 -*-
"""# 1193

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joiEVfDbLsFo5hjRQe5K_mupfAS-fZUP
"""

# 1193 분수 찾기
X = int(input())
row=1

while X>row:
    X-=row
    row+=1
    
if row%2==0:
    a=X
    b=row-X+1
else:
    a=row-X+1
    b=X
    
print(a, '/', b, sep='')