# -*- coding: utf-8 -*-
"""# 16490

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BaL-dj4MN98-9PwSqiUpnAJdskXU5SMF
"""

# 16490 외계인의 침투
a, t = map(int,input().split())
print( abs((a+t) * (a-t)) )