# -*- coding: utf-8 -*-
"""# 2355

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZwPZKcxbnJrwimPkf6gAB60hxtWVc1l
"""

# 2355 시그마
A, B = map(int, input().split())

if A > B:
    temp = A
    A = B
    B = temp

N = B-A
sum = A*(N+1) + N*(N+1)/2

print(int(sum))