# -*- coding: utf-8 -*-
"""# 10870

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rj1r2T62m5PnD05XAII8-7082XG_pWKL
"""

# 10870 피보나치 수 5
n = int(input())
F = [0, 1]

if n >= 2:
    for i in range(2,n+1):
        F.append(F[i-1] + F[i-2])

print(F[n])