# -*- coding: utf-8 -*-
"""# 1978

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yjrohcok4o9Ivdsh3OafMsh0sADZOIVG
"""

# 1978 소수 찾기

N = int(input())

nums = list(map(int, input().split()))
count = 0

for i in nums:
    temp = 1 # 소수가 아니면 0로 바꿔주기

    if i == 1:
        temp = 0
    else:
        for j in range(2,i):
            if (i % j) == 0 :
                temp = 0
                break;

    if temp == 1:
        count += 1

print(count)