# -*- coding: utf-8 -*-
"""# 1003

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S06GRS0WJFfJo2Jy0XcM5RPOOgYWfVMl
"""

# 1003 
import sys
T = int(input()) # 테스트 케이스의 개수
# make list
fib_0 = [1, 0] # 0 출력 횟수의 기본 값
fib_1 = [0, 1] # 1 출력 횟수의 기본 값

for i in range(2, 41):
    fib_0.append(fib_0[i-2]+fib_0[i-1])
    fib_1.append(fib_1[i-2]+fib_1[i-1])
    
for i in range(T):
    N = int(sys.stdin.readline())
    print(fib_0[N], fib_1[N])