# -*- coding: utf-8 -*-
"""# 10699

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sNJ88ZRk-tDziYt6T0nSfg8iSBJ2jG8W
"""

# 10699 오늘 날짜
import datetime
print(str(datetime.datetime.now())[:10])