# -*- coding: utf-8 -*-
"""# 10814

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5dQjhPramtM5BXKcCiBVgJRzmtdfoo4
"""

# 10814 나이순 정렬
import sys
N = int(input())

member = []
for i in range(N):
    age, name = map(str, sys.stdin.readline().split())
    age = int(age)
    member.append((age, name))

member.sort(key = lambda member:(member[0]))

for i in member:
    print(i[0], i[1])