# -*- coding: utf-8 -*-
"""# 11728

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eO5-XgpLULZjhLjc1vU1_P9H7pkjf9kh
"""

# 11728 배열 합치기
N, M = map(int, input().split())    
A = list(map(int, input().split()))
B = list(map(int, input().split()))

A.sort()
B.sort()

i, j = 0, 0
while i<N and j<M:
    if A[i] < B[j]:
        print(A[i], end = ' ')
        i += 1
    else:
        print(B[j], end = ' ')
        j += 1

while i<N:
    print(A[i], end = ' ')
    i += 1

while j<M:
    print(B[j], end = ' ')
    j+=1