# -*- coding: utf-8 -*-
"""# 7770

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lUGGx3xBflAkk6pQ3zcO0dKAucEduLkt
"""

# 7770 아즈텍 피라미드
# 1 6 19 44
#  5 13 25
# 바닥 기준 1 5 13 25
# 바닥 기준  4 8 12
N = int(input())
height = 1
blocks = 1
bottom = 1 # 바닥에 깔려야하는 최소 기준
n = 1

while 1:
    bottom += n*4
    blocks += bottom
    if N >= blocks:
        height += 1
        n += 1
    else:
        break;
print(height)