# -*- coding: utf-8 -*-
"""# 2565

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qrfaz4ycXFmniAEqN33PaFRy4oHOg0Mv
"""

# 2565 전깃줄
import sys
N = int(input()) # 두 전봇대 사이의 전깃줄의 개수
lines = []
dp = [1 for _ in range(N)]

for _ in range(N):
    A, B = map(int,sys.stdin.readline().split())
    lines.append((A, B))

lines.sort(key = lambda x : x[0])

for i in range(1, N):
    for j in range(i):
        if lines[j][1] < lines[i][1]:
            dp[i] = max(dp[i], dp[j]+1)

print(N-max(dp))