# -*- coding: utf-8 -*-
"""# 11053

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VwPnYpSYUes8OEMKIO4ayZNChn9YH_PF
"""

# 11053 가장 긴 증가하는 부분 수열
N = int(input())
A = list(map(int, input().split()))
length_list = [0 for i in range(N)] # 각 숫자까지의 부분수열 길이의 최댓값을 담을 리스트

for i in range(N): 
    for j in range(i): 
        if A[i] > A[j] and length_list[i] < length_list[j]: # i+1번째 전과 비교하기
            length_list[i] = length_list[j]
    length_list[i] += 1

print(max(length_list))