# -*- coding: utf-8 -*-
"""# 10809

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LORTKeuYLQlLO4nafjRZhFYOYrIpLSOy
"""

# 10809 알파벳 찾기
S = input()

alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
check = [-1] * 26

for i in range(len(S)):
    if S[i] in alphabets:
        if check[alphabets.index(S[i])] == -1:
            check[alphabets.index(S[i])] = i

for j in check:
    print(j, end = ' ')