# -*- coding: utf-8 -*-
"""# 9086

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11jbOb8txDYXwXDnc0aNM6eF3cOTlh7Q1
"""

# 9086 문자열

T = int(input())

for i in range(T):
    char = input()
    print(char[0], char[-1], sep='')