# -*- coding: utf-8 -*-
"""# 12738

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgFecwSCoWXsCv4yIm4-DdfPP2KeZ5Ov
"""

# 12738 가장 긴 증가하는 부분 수열3
N = int(input())
A = list(map(int, input().split())) # 수열 A
lis = [-99999999999]

for num in A:
    if lis[-1] < num: # lis의 마지막 값보다 현재 수가 작으면
        lis.append(num) # 마지막 값으로 추가해준다.
    else: # 그렇지 않다면 위치를 찾아서 넣어주자. (이분 탐색)
        start, end = 0, len(lis)
        while start < end:
            mid = (start + end) // 2
            if lis[mid] < num:
                start = mid + 1
            else:
                end = mid
        lis[end] = num

print(len(lis)-1) # 처음 넣었던 값을 빼고 길이 출력