# -*- coding: utf-8 -*-
"""# 1620

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tU9Q70u7wKO3J44RtehlqljSe1VXj1f-
"""

# 1620 나는야 포켓몬 마스터 이다솜
import sys
N, M = map(int, input().split())
pd_idx_to_value = {} 
pd_value_to_idx = {}

for i in range(N):
    pokemon = sys.stdin.readline().strip()
    pd_idx_to_value[i+1] = pokemon
    pd_value_to_idx[pokemon] = i+1

for j in range(M):
    quiz = str(sys.stdin.readline()).strip()

    try:
        print(pd_idx_to_value[int(quiz)])
    except:
        print(pd_value_to_idx[quiz])