# -*- coding: utf-8 -*-
"""# 2953

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4FiQgVjUNgDNIsBolGHgW0N8kdasqQR
"""

# 2953 나는 요리사다
player_list = []

for i in range(5):
    score = list(map(int, input().split())) # 각 평가를 리스트에 저장
    player_list.append(sum(score)) # 평가 점수의 합을 참가자들 순에 맞게 저장

print(player_list.index(max(player_list))+1, max(player_list)) # 우승자의 번호와 그 점수를 출력