# -*- coding: utf-8 -*-
"""# 24039

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hMizKRt_SheDHmb08Tz5izBTrJFvFK-
"""

# 24039 2021은 무엇이 특별할까
N = int(input())
era = [1 for _ in range(10001)]
era[1] = 0

for i in range(2, int(10001**0.5)+1):
    mul = 2
    while (i * mul) <= 10000:
        era[i*mul] = 0
        mul += 1

prime = []
for i in range(1, 10001):
    if era[i]:
        prime.append(i)

i = 0
while True:
    special = prime[i] * prime[i+1]
    if  N < special:
        print(special)
        break
    i+=1