# -*- coding: utf-8 -*-
"""# 11722

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162fC11fsIy6aXf5JFPpClVU01_dXojRy
"""

# 11722 가장 긴 감소하는 부분 수열
N = int(input())
A = list(map(int, input().split()))
dp = [1 for _ in range(N)]

for i in range(1, N):
    for j in range(i):
        if A[i] < A[j]:
            dp[i] = max(dp[i], dp[j] + 1)

print(max(dp))