# -*- coding: utf-8 -*-
"""# 1436

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bpNRlFvnbr9__ui9WleLznP14OrUh0t1
"""

# 1436 영화감독 숌

N = int(input())
cnt = 0
temp = 666

while True:
    if '666' in str(temp):
        cnt += 1
    if cnt == N:
        print(temp)
        break
    temp += 1