# -*- coding: utf-8 -*-
"""# 16396

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hdjqCYlGZAClZLjQOZNrHiPheJhEUnIs
"""

# 16396 선 그리기 => 시간 줄임
N = int(input())
line = {x:0 for x in range(10001)} # 투사된 선

projection = 0
sum = 0

for _ in range(N):
    Xi, Yi = map(int, input().split())
    line[Xi] += 1
    line[Yi] -= 1

for value in line.values():
    projection += value # 선이 끝나면 0이 된다.
    
    if projection > 0: #선이 이어지는 동안
        sum += 1 

print(sum)