# -*- coding: utf-8 -*-
"""# 1011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11aQi5_R70HGRAtogoXKhNPPsDzvLMSEI
"""

# 1011 Fly me to the Alpha Centauri
T = int(input())

for _ in range(T):
    x, y = map(int, input().split()) 
    dist = y - x # 이동해야하는 거리
    all_move = 0 # 이동한 거리
    cnt = 0  # 이동 횟수
    k = 1 # 이동 가능한 거리 처음 값 1
    
    while all_move < dist : # 이동한 거리가 이동해야하는 거리보다 작으면
        cnt += 1
        all_move += k  # count 수에 해당하는 move를 더함
        if cnt % 2 == 0 :  # cnt가 2의 배수일 때, 
            k += 1  
    print(cnt)