# -*- coding: utf-8 -*-
"""# 2750

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LO4FND5nzJImGc6QvDRCo3djr3Rl4umR
"""

# 2750 수 정렬하기
N = int(input())
nums = []
for i in range(N):
    nums.append(int(input()))

nums.sort()

for j in range(N):
    print(nums[j])