# -*- coding: utf-8 -*-
"""# 9094

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAdv6Ynhu3ViE2haU3v4fd1RdzO423AV
"""

# 9094 수학적 호기심
import sys
T = int(input())

for _ in range(T):
    n, m = map(int, sys.stdin.readline().split())
    ans = 0

    for a in range(1,n-1):
        for b in range(a+1, n):
            if  ((a**2 + b**2 + m) % (a*b))  == 0:
                ans += 1

    print(ans)