# -*- coding: utf-8 -*-
"""#10818

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Oksfzkovo9cwF5Fmhi3gq0MjOr2XWmu
"""

# 10818 최소, 최대

N = int(input()) # N 개의 정수의 N을 입력받는다.
numbers = list(map(int, input().split())) # list 형으로 정수들을 입력받는다. 

print(min(numbers), max(numbers))