# -*- coding: utf-8 -*-
"""# 17386

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BL9XpiNdW6IJ3MrMX1nxCABnu0k4iRyU
"""

# 17386 선분 교차 1
x1, y1, x2, y2 = map(int, input().split()) # P1 P2
x3, y3, x4, y4 = map(int, input().split()) # P3 P4

def direction(x1, y1, x2, y2, x3, y3):
    L1 = (x1*y2) + (x2*y3) + (x3*y1)
    L2 = (y1*x2) + (y2*x3) + (y3*x1)

    if (L1-L2) < 0:
       return 1
    else:
        return -1 

P123 = direction(x1, y1, x2, y2, x3, y3)
P124 = direction(x1, y1, x2, y2, x4, y4)
P341 = direction(x3, y3, x4, y4, x1, y1)
P342 = direction(x3, y3, x4, y4, x2, y2)

if P123*P124 <= 0 and P341*P342 <= 0:
    print(1)
else:
    print(0)