# -*- coding: utf-8 -*-
"""# 9550

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ioubWYkTF_87X81sVk_MLuSUZW29yxxB
"""

# 9550 아이들은 사탕을 좋아해
T = int(input()) # 테스트 케이스

for i in range(T):
    sum = 0 # 각 케이스마다 참석할 수 있는 아이의 수
    N, K = map(int, input().split())
    candy = list(map(int, input().split()))

    for j in range(N):
        sum += candy[j] // K  

    print(sum)