# -*- coding: utf-8 -*-
"""# 11654

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUns48sfqk_ggJJVv6lAT219R1CDNZEr
"""

# 11654 아스키 코드
print(ord(input()))