# -*- coding: utf-8 -*-
"""# 7785

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ctQpYTfVY9qFDZaGshIObocKhThBOD_F
"""

# 7785 회사에 있는 사람
import sys
n = int(input()) # 출입 기록의 수
work = set() # 집합으로 받자. (애초에 동명이인이 없다.)

for _ in range(n):
    log = sys.stdin.readline().split()
    
    if log[1] == 'enter':
        work.add(log[0])
    else:
        work.remove(log[0])

work = sorted(list(work), reverse = True) # 사전 역순으로 출력

for name in work:
    print(name)