# -*- coding: utf-8 -*-
"""#1010

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16kK3utZsekiI78tlJn0V0rlPAiH_YYZU
"""

# 1010 다리 놓기

def factorial(x): # 팩토리얼 구현
    n = 1
    for i in range(1,x+1):
        n = n*i
    return n


def comb(m,n): # 조합 구현
    num = factorial(m) / (factorial(m-n) * factorial(n))
    return int(num)

T = int(input()) # Test Case 수 입력

for i in range(T):
    N, M = map(int,input().split())
    print(comb(M,N))