# -*- coding: utf-8 -*-
"""# 7568

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMvV-CA5Qb8yhJnmBncttHk_mqPOsJA5
"""

# 7568 덩치

N = int(input())
info = []

for i in range(N):
    x, y = map(int, input().split())
    info.append((x,y))

for j in info:
    rank = 1

    for k in info:
        if (j[0] < k[0]) and (j[1] < k[1]):
            rank += 1
    print(rank, end = " ")