# -*- coding: utf-8 -*-
"""# 25238

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q189m4uhZV4kIqkoG3XLdwMhYMezVVj5
"""

# 25238 가희와 방어율 무시

a, b = map(int, input().split())

new_a = a * (100-b)/100

if new_a >= 100:
    print(0)
else:
    print(1)