# -*- coding: utf-8 -*-
"""# 10826

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmWw6-91lxkVmoaBcGXhd0SdBheZ04iQ
"""

# 10826피보나치 수 4
def fibonacci(n):
    x, y = 0, 1
    for i in range(n):
        x, y = y, x+y
    return x

print(fibonacci(int(input())))