# -*- coding: utf-8 -*-
"""# 21592

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbmvFc9U55OZY-KIuuXwPVsx9NGPDBb6
"""

import sys
def solve():
    n = int(input())

    for _ in range(n):
        string = sys.stdin.readline().rstrip() 
        strings.append(string)

    least = min(strings, key=len)

    for strlen in range(len(least), -1, -1): # 첫번째 문자열의 길이부터 0까지 -1 단위로
        for i in range(len(least)-strlen+1):
            idx = i+strlen
            substring = least[i:idx]
        
            if all(substring in x for x in strings]): # 모든 문자열들에 substring이 들어간다면
                print(strlen)
                return

solve()