# -*- coding: utf-8 -*-
"""# 1789

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5Ai671OWCNywPbH74KXe4mwEvxIeaCF
"""

# 1789 수들의 합
S = int(input())
N = 0

while (N*(N+1) / 2) <= S:
    N += 1

print(N-1)