# -*- coding: utf-8 -*-
"""# 16394

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1szr7iBSK-ih6x_WDAU7pJGySL7rzMNQN
"""

# 16394 홍익대학교

N = int(input())

print(N-1946)