# -*- coding: utf-8 -*-
"""# 1213

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5vsC2ih_XPck7gbNi1ppOcxv4e2WHwG
"""

# 1213 팰린드롬 만들기
from collections import deque

def palindrome(seq):
    N = len(seq)

    for i in range(N//2):
        if seq[i] != seq[-(i+1)]:
            return False
    return True

left, middle, right = "", "", ""
seq = list(input())
seq.sort()

seq = deque(seq)

while seq:
    if len(seq) >= 2:
        if seq[0] == seq[1]:
            left += seq.popleft()
            right += seq.popleft()
        elif seq[0] != seq[1]:
            middle += seq.popleft()
    else:
        middle += seq.popleft()

ans = left + middle
for i in range(len(left)):
    ans += left[-(i+1)]

if palindrome(ans):
    print(ans)
else:
    print("I'm Sorry Hansoo")