# -*- coding: utf-8 -*-
"""# 15700

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzjaEhul91tqfHRR1Je5OFFOQRTKuvE0
"""

# 15700
N, M = map(int, input().split())
print( (N*M) // 2 )