# -*- coding: utf-8 -*-
"""# 25345

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hRBoeqs7f-lWbjkQz8gNjA_lV8HjaSah
"""

# 25345 루나의 게임 세팅
N, K = map(int, input().split())
height = list(map(int, input().split()))
dp = [[0 for _ in range(2001)] for _ in range(2001)]
mod = 10**9 + 7

for i in range(N+1):
    dp[i][0] = 1;
    for j in range(1, i+1):
        dp[i][j] = (dp[i-1][j-1] + dp[i-1][j]) % mod

ans = dp[N][K]

for _ in range(K-1): 
    ans = (ans * 2) % mod

print(ans)