# -*- coding: utf-8 -*-
"""#1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VWvIKtsB6DhWwb7tbe9U8obm6_abP8rf
"""

# 1004 어린 왕자
T = int(input()) # 테스트 케이스 입력

for i in range(T): 
    x1, y1, x2, y2 = map(int, input().split(' '))
    cnt = 0 # 진입/이탈 횟수
    n = int(input()) # 행성계의 개수 n

    for j in range(n):
        cx, cy, r = map(int, input().split(' '))
        dist1 = ( (cx-x1)**2 + (cy-y1)**2 ) ** 0.5 # 출발점과 주어진 점의 거리
        dist2 = ( (cx-x2)**2 + (cy-y2)**2 ) ** 0.5 # 도착점과 주어진 점의 거리

        if (dist1 < r and dist2 > r) or (dist1 > r and dist2 < r): # 출발 or 도착 점 중 하나만 행성계에 속하는 경우
            cnt += 1
            
    print(cnt) # 진입/이탈 횟수 출력