# -*- coding: utf-8 -*-
"""# 3009

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_3H-nWxkB0gXYK-tsH8L5bf8fc5X01-
"""

# 3009 네 번째 점
xs = [] # x 좌표 값들을 저장
ys = [] # y 좌표 값들을 저장

for i in range(3): # 기존의 x, y 좌표들을 입력받는다.
    x, y = map(int, input().split()) 
    xs.append(x)
    ys.append(y)

for j in range(3): # x, y 좌표들의 각 값으로 카운팅 했을 때 하나라면 네번째 x, y 좌표는 결정
    if xs.count(xs[j]) == 1: 
        forth_x = xs[j]
    if ys.count(ys[j]) == 1:
        forth_y = ys[j]

print(forth_x, forth_y)