# -*- coding: utf-8 -*-
"""# 16953

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rsbLvHBSinFp3TDrwE7yHtUls7Pl7euF
"""

# 16953 A->B

A, B = map(int, input().split()) # A < B
cnt = 1 # 연산의 최솟값에 1 을 더해서 출력하라는 조건

# A->B 의 과정을 역으로 생각
while (A != B):
    if (B%2 == 0) and (B//2 >= A):
        B = B//2
        cnt += 1
    elif (B%10 == 1) and (B//10 >= A):
        B = B//10
        cnt += 1
    else:
        cnt = -1
        break
    
print(cnt)