# -*- coding: utf-8 -*-
"""# 1094

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vW0LbJ8p-1lGpohGg_t42ikPTFoX0sfS
"""

# 1094 막대기
binary_X = format(int(input()), 'b') # 입력받은 수 X를 바로 이진수로 변환해준다.
cnt = 0 
for i in str(binary_X): 
    if i == '1': # 자리마다 1이 있으면 카운팅
        cnt += 1

print(cnt)