# -*- coding: utf-8 -*-
"""# 2869

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEM3n5RPAYTURKBevugbRCi5mudZMKz2
"""

# 2869 달팽이는 올라가고 싶다  ==> 시간초과

A, B, V = map(int, input().split(' ')) # 낮에 올라가는 거리, 밤에 미끄러지는 거리,  높이 순

height = 0
d = 0 

while 1:
  d += 1
  height += A
  if height >= V:
    break
  height -= B

print(d)

# A, B, V 범위가 1,000,000,000 까지라서 이렇게 돌리면 시간초과인듯.

A, B, V = map(int, input().split(' ')) # 낮에 올라가는 거리, 밤에 미끄러지는 거리,  높이 순

h = A - B  # 하루에 올라가는 거리
case1 = int((V - A) / h + 1)  # 나누어 떨어질 때
case2 = int((V - A) / h + 2)  # 안 나누어 떨어질 때
d = (V - A) % h

if d == 0 :
  print(case1)
else:
  print(case2)


# 정답처리
