# -*- coding: utf-8 -*-
"""# 1100

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXhbq51feXhpczpswXhaCi4JzrrxltjM
"""

# 1100 하얀 칸
chess = [] # 체스 판을 입력받을 준비
cnt = 0 # 하얀 칸에 말이 있는 경우의 수
for i in range(8):
    chess.append(input())

for i in range(8):
    for j in range(8):
        if (i+j) % 2 == 0 and chess[i][j] == 'F': # (i,j)번째에서 i+j 가 짝수인 경우 흰색판이다.
            cnt += 1

print(cnt)