# -*- coding: utf-8 -*-
"""#9626

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oNTcjy6XuKUmuf-tnX_hCfJMaC0rfC1Q
"""

# 9626 크로스워드 퍼즐

M, N = map(int, input().split())
U, L, R, D = map(int, input().split())
word_list = [] 
deco = ['#', '.']

for i in range(M):
    word = input()
    word_list.append(word)

for j in range(U):
    for k in range(N+L+R):
        print(deco[(j+k)%2], end='')
    print()

for i in range(M):

    for l in range(L):
        print(deco[(U+i+l)%2], end='')
    print(word_list[i], end='')

    for r in range(R):
        print(deco[(U+N+L+i+r)%2], end='')
    print()

for j in range(D):
    for k in range(N+L+R):
        print(deco[(U+M++j+k)%2], end='')
    if j == (D-1):
        break
    print()