# -*- coding: utf-8 -*-
"""# 5598

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Fy1JUENH1cbe4AuhqrH3kXbwI5n8dzG
"""

# 5598 카이사르 암호
password = ""

for c in input():
    c = ord(c)
    if (c <= 67): # A, B, C
        c += 23
    else:
        c -= 3
    password += chr(c)

print(password)