# -*- coding: utf-8 -*-
"""# 13116

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTNoYMZiwPs4Df7-aub3rPtCJU3k6fYm
"""

# 13116 30번
T = int(input())

for _ in range(T):
    A, B = map(int, input().split())

    while A != B:
        if A > B:
            A //= 2
        else:
            B //= 2
    print(A*10)