# -*- coding: utf-8 -*-
"""# 10773

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-1P6rLaVEslSC3FpxxBBGLeVPzJXu49
"""

# 10773 제로
import sys
K = int(input())
stack = []

for _ in range(K):
    num = int(sys.stdin.readline())
    #num = int(input())
    if num:
        stack.append(num)
    else:
        stack.pop()

print(sum(stack))