# -*- coding: utf-8 -*-
"""# 11718

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCDgcGKFkl8hTPkODNTwgpGFXkuoWyin
"""

# 11718 그대로 출력하기
while 1:
    try:
        print(input())
    except EOFError:
        break;