# -*- coding: utf-8 -*-
"""# 4948

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GSnxqWx9CeNZ8Ni0FSEay3buh59M7aMu
"""

# 4948 베르트랑 공준
import sys

while True:
    n = int(sys.stdin.readline())

    if n == 0: # 입력이 0 이면 멈춤
        break

    cnt = 0

    for i in range(n+1, 2*n+1):
        if i == 2:
            cnt += 1
        else:
            for j in range(2, int(i**0.5) + 1):
                if i % j == 0:
                    break
            else:
                cnt += 1    

    print(cnt)