# -*- coding: utf-8 -*-
"""# 11723

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qw3i_O-NRfmyCU6hO8zkYyoontHylc_2
"""

# 11723 집합
import sys
M = int(input())
S = [0 for _ in range(21)] # Set init

for _ in range(M):
    op = sys.stdin.readline().rstrip().split()

    # operations
    if op[0] == 'add':
        S[int(op[1])] = 1

    elif op[0] == 'remove':
        S[int(op[1])] = 0

    elif op[0] == 'check':
        print(S[int(op[1])])

    elif op[0] == 'toggle':
        if S[int(op[1])]:
            S[int(op[1])] = 0
        else:
            S[int(op[1])] = 1

    elif op[0] == 'all':
        S = [1 for _ in range(21)]

    elif op[0] == 'empty':
        S = [0 for _ in range(21)]