# -*- coding: utf-8 -*-
"""# 2470

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zodiw84kbhoDOshK3mC-oRY6IuuQ_wHa
"""

# 2470 두 용액
N = int(input())
value = list(map(int, input().split()))

value.sort() # 이분 탐색 위해서 정렬

# initialization
start, end = 0, N-1
ans1, ans2 = value[start], value[end]
threshold = 2000000001

# Solution
while start < end:
    sumValue = value[start] + value[end]
    absSum = abs(sumValue)

    if absSum < threshold: # 0에 더 가까우면
        threshold = absSum # 저장
        ans1, ans2 = value[start], value[end]

    if sumValue < 0: # 0보다 작으면
        start += 1 # 값 키워보자
    else:
        end -= 1

print(ans1, ans2)